import { KeyDef } from "@/types";

export const KEYBOARD_MAP: Record<string, string> = {
  "0": "0",
  "1": "1",
  "2": "2",
  "3": "3",
  "4": "4",
  "5": "5",
  "6": "6",
  "7": "7",
  "8": "8",
  "9": "9",
  ".": ".",
  "+": "+",
  "-": "−",
  "*": "×",
  "/": "÷",
  Enter: "=",
  "=": "=",
  Backspace: "⌫",
  Delete: "⌫",
  Escape: "AC",
  "%": "%",
  "^": "xⁿ",
  s: "sin",
  c: "cos",
  t: "tan",
  l: "log",
  n: "ln",
  r: "√",
  "!": "n!",
  p: "π",
  e: "e",
  m: "MR",
  M: "M+",
  "(": "(",
  ")": ")",
};

export const KEYS: (KeyDef | "spacer")[][] = [
  [
    { label: "MC", action: { type: "MEMORY_CLEAR" }, type: "memory" },
    { label: "MR", action: { type: "MEMORY_RECALL" }, type: "memory", keyboard: "m" },
    { label: "M+", action: { type: "MEMORY_PLUS" }, type: "memory", keyboard: "M" },
    { label: "M−", action: { type: "MEMORY_MINUS" }, type: "memory" },
    { label: "(", action: { type: "OPEN_PAREN" }, type: "utility", keyboard: "(" },
    { label: ")", action: { type: "CLOSE_PAREN" }, type: "utility", keyboard: ")" },
  ],
  [
    { label: "x²", action: { type: "SQUARE" }, type: "scientific" },
    { label: "x³", action: { type: "CUBE" }, type: "scientific" },
    { label: "xⁿ", action: { type: "POWER" }, type: "scientific", keyboard: "^" },
    { label: "1/x", action: { type: "RECIPROCAL" }, type: "scientific" },
    { label: "√", action: { type: "SQRT" }, type: "scientific", keyboard: "r" },
    { label: "%", action: { type: "PERCENT" }, type: "scientific", keyboard: "%" },
  ],
  [
    { label: "sin", action: { type: "SCIENCE_FN", payload: "sin" }, type: "scientific", keyboard: "s" },
    { label: "cos", action: { type: "SCIENCE_FN", payload: "cos" }, type: "scientific", keyboard: "c" },
    { label: "tan", action: { type: "SCIENCE_FN", payload: "tan" }, type: "scientific", keyboard: "t" },
    { label: "log", action: { type: "SCIENCE_FN", payload: "log" }, type: "scientific", keyboard: "l" },
    { label: "ln", action: { type: "SCIENCE_FN", payload: "ln" }, type: "scientific", keyboard: "n" },
    { label: "n!", action: { type: "FACTORIAL" }, type: "scientific", keyboard: "!" },
  ],
  [
    { label: "7", action: { type: "INPUT_NUMBER", payload: "7" }, type: "number", keyboard: "7" },
    { label: "8", action: { type: "INPUT_NUMBER", payload: "8" }, type: "number", keyboard: "8" },
    { label: "9", action: { type: "INPUT_NUMBER", payload: "9" }, type: "number", keyboard: "9" },
    { label: "÷", action: { type: "SET_OPERATOR", payload: "÷" }, type: "operator", keyboard: "/" },
    { label: "AC", action: { type: "CLEAR" }, type: "utility", keyboard: "Escape" },
    { label: "⌫", action: { type: "DELETE" }, type: "utility", keyboard: "Backspace" },
  ],
  [
    { label: "4", action: { type: "INPUT_NUMBER", payload: "4" }, type: "number", keyboard: "4" },
    { label: "5", action: { type: "INPUT_NUMBER", payload: "5" }, type: "number", keyboard: "5" },
    { label: "6", action: { type: "INPUT_NUMBER", payload: "6" }, type: "number", keyboard: "6" },
    { label: "×", action: { type: "SET_OPERATOR", payload: "×" }, type: "operator", keyboard: "*" },
    { label: "π", action: { type: "PI" }, type: "scientific", keyboard: "p" },
    { label: "e", action: { type: "EULER" }, type: "scientific", keyboard: "e" },
  ],
  [
    { label: "1", action: { type: "INPUT_NUMBER", payload: "1" }, type: "number", keyboard: "1" },
    { label: "2", action: { type: "INPUT_NUMBER", payload: "2" }, type: "number", keyboard: "2" },
    { label: "3", action: { type: "INPUT_NUMBER", payload: "3" }, type: "number", keyboard: "3" },
    { label: "−", action: { type: "SET_OPERATOR", payload: "−" }, type: "operator", keyboard: "-" },
    { label: "±", action: { type: "TOGGLE_SIGN" }, type: "utility" },
    { label: "EXP", action: { type: "EXPT" }, type: "scientific" },
  ],
  [
    { label: "0", action: { type: "INPUT_NUMBER", payload: "0" }, type: "number", keyboard: "0" },
    { label: ".", action: { type: "INPUT_DECIMAL" }, type: "number", keyboard: "." },
    { label: "", action: { type: "CLEAR" }, type: "utility" }, // spacer
    { label: "+", action: { type: "SET_OPERATOR", payload: "+" }, type: "operator", keyboard: "+" },
    "spacer",
    { label: "=", action: { type: "COMPUTE" }, type: "equals", keyboard: "Enter", span: 2 },
  ],
];

export const SCIENTIFIC_FN_LABELS: Record<string, string> = {
  sin: "sin",
  cos: "cos",
  tan: "tan",
  log: "log",
  ln: "ln",
  sqrt: "√",
  square: "x²",
  cube: "x³",
  reciprocal: "1/x",
  factorial: "n!",
  percent: "%",
};
